import Head from "next/head";
import Cart from "../components/Cart";
import Navbar from "../components/layouts/Navbar";
import Products from "../components/Products";
import Sidebar from "../components/Sidebar";
import styles from "../styles/main.module.css";
import AddProduct from "../components/layouts/Modals/AddProduct";
import { useRouter } from "next/router";
import Transition from "../components/UI/Transition";
import { useSelector, useDispatch } from "react-redux";
import { useEffect } from "react";
import { getProducts } from "../redux/actions/products.action";
import CheckoutModal from "../components/layouts/Modals/CheckoutModal/CheckoutModal";

export default function Home() {
  const { add_product_modal, success_modal } = useSelector((state) => state.ui);
  const dispatch = useDispatch();
  const { products } = useSelector((state) => state.products);

  useEffect(() => {
    if (products.length === 0) {
      dispatch(getProducts());
    }
  }, []);

  return (
    <div className="h-full bg-blue-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Transition inprop={add_product_modal}>
        <AddProduct />
      </Transition>
      <Transition inprop={success_modal}>
        <CheckoutModal />
      </Transition>

      <Navbar />

      <main
        className={`grid-cols-4 grid p-2 h-auto overflow-hidden gap-2 ${styles.main}`}
      >
        <Sidebar />
        <Products />
        <Cart />
      </main>
    </div>
  );
}
