import Head from "next/head";
import { useState } from "react";
import Cart from "../components/Cart";
import Navbar from "../components/layouts/Navbar";
import Products from "../components/Products";
import Sidebar from "../components/Sidebar";
import styles from '../styles/main.module.css'

export default function Home() {
  const [cartOpen, setcartOpen] = useState(true);

  const toggleCartItems = ()=>setcartOpen((prev)=>!prev);

  return (
    <div className="h-full bg-blue-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`grid-cols-4 grid p-2 h-auto overflow-hidden gap-2 ${styles.main}`}>
        <Sidebar/>
        <Products wide={!cartOpen}/>
        <Cart open={cartOpen} close={toggleCartItems}/>
      </main>
    </div>
  );
}
